version: "3.4"
services:
  ons-postgres:
    container_name: postgres
    image: postgres:13
    command: ["-c", "shared_buffers=256MB", "-c", "max_connections=500"]
    ports:
      - "${EX_POSTGRES_PORT}:5432"
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

  sftp:
    container_name: sftp
    image: atmoz/sftp
    volumes:
      - ~/Documents/sftp/supplier_A/print_services/:/home/centos/supplier_A/print_services/
      - ~/Documents/sftp/supplier_B/print_services/:/home/centos/supplier_B/print_services/
      - ./dummy_keys/dummy_rsa.pub:/home/centos/.ssh/keys/dummy_rsa.pub:ro
    ports:
      - "${EX_SFTP_PORT}:22"
    command: centos::2000

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    ports:
      - "80:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=ons@ons.gov
      - PGADMIN_DEFAULT_PASSWORD=secret
    links:
      - ons-postgres:postgres

  pubsub-emulator:
    container_name: pubsub-emulator
    image: eu.gcr.io/ssdc-rm-ci/rm/gcloud-pubsub-emulator:latest
    ports:
      - "8538:8538"

  notifystub:
    container_name: notifystub
    image: eu.gcr.io/ssdc-rm-ci/rm/census-rm-notify-stub:latest
    ports:
      - "8917:5000"

networks:
  ssdcrmdockerdev_default:
    external: true
