version: "3.4"
services:
  redis:
    container_name: redis
    image: redis
    ports:
      - "6379:6379"

  firestore-emulator:
    container_name: firestore-emulator
    image: europe-west2-docker.pkg.dev/ssdc-rm-ci/docker/gcloud-firestore-emulator:latest
    ports:
      - "8542:8540"

  mock-service:
    container_name: mock-service
    image: europe-west2-docker.pkg.dev/ons-ci-int/int-docker-release/mock-service:latest
    ports:
      - "8163:8162"

  mock-envoy:
    container_name: mock-envoy
    image: europe-west2-docker.pkg.dev/ons-ci-int/int-docker-release/mock-envoy:latest
    ports:
      - "8181:8181"

networks:
  ssdcrmdockerdev_default:
    external: true
