version: "3.4"
services:
  ons-postgres:
    container_name: postgres
    image: europe-west2-docker.pkg.dev/ssdc-rm-ci/docker/ssdc-rm-dev-common-postgres:latest
    command: [ "-c", "shared_buffers=256MB", "-c", "max_connections=500" ]
    ports:
      - "${EX_POSTGRES_PORT}:5432"
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1000M
        reservations:
          cpus: '0.5'
          memory: 1000M

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    ports:
      - "81:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=ons@ons.gov
      - PGADMIN_DEFAULT_PASSWORD=secret
    links:
      - ons-postgres:postgres
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: 250M
        reservations:
          cpus: '0.2'
          memory: 250M

  pubsub-emulator:
    container_name: pubsub-emulator
    image: europe-west2-docker.pkg.dev/ssdc-rm-ci/docker/gcloud-pubsub-emulator:latest
    ports:
      - "8538:8538"
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: 500M
        reservations:
          cpus: '0.3'
          memory: 500M

  notifystub:
    container_name: notifystub
    image: europe-west2-docker.pkg.dev/ssdc-rm-ci/docker/ssdc-rm-notify-stub:latest
    ports:
      - "8917:5000"
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: 200M
        reservations:
          cpus: '0.2'
          memory: 200M

  firestore-emulator:
    container_name: firestore-emulator
    image: europe-west2-docker.pkg.dev/ssdc-rm-ci/docker/gcloud-firestore-emulator:latest
    ports:
      - "8542:8540"
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: 400M
        reservations:
          cpus: '0.2'
          memory: 400M

  sdx-receipt-adapter:
    container_name: sdx-receipt-adapter
    image: europe-west2-docker.pkg.dev/ssdc-rm-ci/docker/sdx-receipt-adapter:latest
    ports:
      - "8100:8100"
    environment:
      - PROJECT_ID=our-project
      - RM_RECEIPT_TOPIC_ID=event_receipt
      - PUBSUB_PUBLISH_CONFIRMATION_TIMEOUT=30
      - GOOGLE_APPLICATION_CREDENTIALS=/gcp/config/google-credentials.json
      - PUBSUB_EMULATOR_HOST=pubsub-emulator:8538
    volumes:
      - type: bind
        source: ./fake-service-account.json # The pubsub client used by the sdx receipt adapter requires google credentials, give it a dummy account locally
        target: /gcp/config/google-credentials.json
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: 100M
        reservations:
          cpus: '0.2'
          memory: 100M

networks:
  ssdcrmdockerdev_default:
    external: true
