version: "3.4"
services:
  ons-postgres:
    container_name: postgres
    image: europe-west2-docker.pkg.dev/ssdc-rm-ci/docker/ssdc-rm-dev-common-postgres:latest
    command: [ "-c", "shared_buffers=256MB", "-c", "max_connections=500" ]
    ports:
      - "${EX_POSTGRES_PORT}:5432"

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    ports:
      - "80:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=ons@ons.gov
      - PGADMIN_DEFAULT_PASSWORD=secret
    links:
      - ons-postgres:postgres

  pubsub-emulator:
    container_name: pubsub-emulator
    image: europe-west2-docker.pkg.dev/ssdc-rm-ci/docker/gcloud-pubsub-emulator:latest
    ports:
      - "8538:8538"

  notifystub:
    container_name: notifystub
    image: europe-west2-docker.pkg.dev/ssdc-rm-ci/docker/ssdc-rm-notify-stub:latest
    ports:
      - "8917:5000"

  firestore-emulator:
    container_name: firestore-emulator
    image: europe-west2-docker.pkg.dev/ssdc-rm-ci/docker/gcloud-firestore-emulator:latest
    ports:
      - "8542:8540"

  redis:
    container_name: redis
    image: redis
    ports:
      - "6379:6379"

  mock-service:
    container_name: mock-service
    image: europe-west2-docker.pkg.dev/ons-ci-int/int-docker-release/mock-service:latest
    ports:
      - "8163:8162"

networks:
  ssdcrmdockerdev_default:
    external: true
