version: "3.4"
services:
  caseprocessor:
    container_name: caseprocessor
    image: europe-west2-docker.pkg.dev/ssdc-rm-ci/docker/ssdc-rm-caseprocessor:3267-get-a-rough-version-of-lifecycle-stuff-working
    external_links:
      - postgres
      - uacqid
      - pubsub-emulator
    environment:
      - SPRING_CLOUD_GCP_PUBSUB_EMULATOR_HOST=pubsub-emulator:8538
      - SPRING_CLOUD_GCP_PUBSUB_PROJECT-ID=our-project
      - QUEUECONFIG_SHARED-PUBSUB-PROJECT=shared-project
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:${POSTGRES_PORT}/${POSTGRES_HOST}?sslmode=disable
      - UACSERVICE_CONNECTION_HOST=${UAC_HOST}
      - UACSERVICE_CONNECTION_PORT=${UAC_PORT}
      - EXCEPTIONMANAGER_CONNECTION_HOST=${EXCEPTIONMANAGER_HOST}
      - EXCEPTIONMANAGER_CONNECTION_PORT=${EXCEPTIONMANAGER_PORT}
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
      - CASEREFGENERATORKEY=${CASEREFGENERATORKEY}
      - RAS-RM-PARTY-SERVICE_CONNECTION_HOST=host.docker.internal
      - RAS-RM-CASE-SERVICE_CONNECTION_HOST=host.docker.internal
      - QUEUECONFIG_RAS-RM-PUBSUB-PROJECT=ras-rm-project
    healthcheck:
      test: [ "CMD", "find", "/tmp/case-processor-healthy", "-mmin", "-1" ]
      interval: 60s
      timeout: 10s
      retries: 10
      start_period: 45s


  caseapi:
    container_name: caseapi
    image: europe-west2-docker.pkg.dev/ssdc-rm-ci/docker/ssdc-rm-case-api:3267-get-a-rough-version-of-lifecycle-stuff-working
    ports:
      - "${CASE_API_PORT}:8161"
    external_links:
      - postgres
      - pubsub-emulator
    environment:
      - SPRING_CLOUD_GCP_PUBSUB_EMULATOR_HOST=pubsub-emulator:8538
      - SPRING_CLOUD_GCP_PUBSUB_PROJECT_ID=our-project
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:${POSTGRES_PORT}/${POSTGRES_HOST}?sslmode=disable
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
      - UACSERVICE_CONNECTION_HOST=${UAC_HOST}
      - UACSERVICE_CONNECTION_PORT=${UAC_PORT}
    restart: always
    volumes:
      - ./java_healthcheck:/opt/healthcheck/
    healthcheck:
      test: [ "CMD", "java", "/opt/healthcheck/HealthCheck.java", "http://localhost:8161/actuator/health" ]
      interval: 60s
      timeout: 10s
      retries: 4
      start_period: 50s


  uacqid:
    container_name: uacqid
    image: europe-west2-docker.pkg.dev/ssdc-rm-ci/docker/ssdc-rm-uac-qid-service
    ports:
      - "${UAC_PORT}:8164"
    external_links:
      - postgres
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:${POSTGRES_PORT}/${POSTGRES_HOST}?sslmode=disable
      - JAVA_TOOL_OPTIONS=-Xmx128m -Xdebug -Dspring.profiles.active=dev
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
    restart: always
    volumes:
      - ./java_healthcheck:/opt/healthcheck/
    healthcheck:
      test: [ "CMD", "java", "/opt/healthcheck/HealthCheck.java", "http://localhost:8164/actuator/health" ]
      interval: 60s
      timeout: 10s
      retries: 4
      start_period: 30s


  exceptionmanager:
    container_name: exceptionmanager
    image: europe-west2-docker.pkg.dev/ssdc-rm-ci/docker/ssdc-rm-exception-manager
    ports:
      - "${EXCEPTIONMANAGER_PORT}:8666"
    restart: always
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:${POSTGRES_PORT}/${POSTGRES_HOST}?sslmode=disable
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - ./java_healthcheck:/opt/healthcheck/
    healthcheck:
      test: [ "CMD", "java", "/opt/healthcheck/HealthCheck.java", "http://localhost:8666/actuator/health" ]
      interval: 60s
      timeout: 10s
      retries: 4
      start_period: 30s


  exportfileservice:
    container_name: exportfileservice
    image: europe-west2-docker.pkg.dev/ssdc-rm-ci/docker/ssdc-rm-export-file-service
    external_links:
      - pubsub-emulator
    environment:
      - READINESS_FILE_PATH=/tmp/ready
      - ENVIRONMENT=DEV
      - EXCEPTIONMANAGER_CONNECTION_HOST=${EXCEPTIONMANAGER_HOST}
      - EXCEPTIONMANAGER_CONNECTION_PORT=${EXCEPTIONMANAGER_PORT}
      - DESTINATION_CONFIG_JSON_PATH=/home/export-file-service/dummy_destination_config.json
      - DESTINATION_KEY_DIRECTORY=/home/export-file-service/dummy_keys
      - DB_HOST=${POSTGRES_HOST}
      - DB_PORT=${POSTGRES_PORT}
      - DB_USERNAME=${POSTGRES_USERNAME}
      - DB_PASSWORD=${POSTGRES_PASSWORD}
      - DB_DATABASE=${POSTGRES_DATABASE}
      - FILE_UPLOAD_DESTINATION=/home/export-file-service/export_files
      - FILE_UPLOAD_MODE=LOCAL
    restart: always
    healthcheck:
      test: sh -c "[ -f /tmp/ready ]"
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 50s
    volumes:
      - ./dummy_keys:/home/export-file-service/dummy_keys
      - ./dummy_destination_config.json:/home/export-file-service/dummy_destination_config.json
      - ~/Documents/export_files:/home/export-file-service/export_files

  supporttool:
    container_name: supporttool
    image: europe-west2-docker.pkg.dev/ssdc-rm-ci/docker/ssdc-rm-support-tool:3267-get-a-rough-version-of-lifecycle-stuff-working
    ports:
      - "9999:9999"
    external_links:
      - pubsub-emulator
      - postgres
    environment:
      - SPRING_CLOUD_GCP_PUBSUB_EMULATOR_HOST=pubsub-emulator:8538
      - SPRING_CLOUD_GCP_PUBSUB_PROJECT-ID=our-project
      - QUEUECONFIG_SHARED-PUBSUB-PROJECT=shared-project
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:${POSTGRES_PORT}/${POSTGRES_HOST}?sslmode=disable
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
      - NOTIFYSERVICE_CONNECTION_HOST=${NOTIFY_SERVICE_HOST}
      - NOTIFYSERVICE_CONNECTION_PORT=${NOTIFY_SERVICE_PORT}
      - DUMMYUSERIDENTITY=${DUMMY_USER}
      - DUMMYUSERIDENTITY-ALLOWED=true
      - EXPORTFILEDESTINATIONCONFIGFILE=/home/supporttool/dummy_destination_config.json
      - EXCEPTIONMANAGER_CONNECTION_HOST=${EXCEPTIONMANAGER_HOST}
      - EXCEPTIONMANAGER_CONNECTION_PORT=${EXCEPTIONMANAGER_PORT}
      - RAS-RM-SAMPLE-SERVICE_CONNECTION_HOST=host.docker.internal
    restart: always
    healthcheck:
      test: [ "CMD", "java", "/opt/healthcheck/HealthCheck.java", "http://localhost:9999/actuator/health" ]
      interval: 60s
      timeout: 10s
      retries: 4
      start_period: 50s
    volumes:
      - ./java_healthcheck:/opt/healthcheck/
      - ./dummy_destination_config.json:/home/supporttool/dummy_destination_config.json

  rops:
    container_name: rops
    image: europe-west2-docker.pkg.dev/ssdc-rm-ci/docker/ssdc-rm-response-operations
    ports:
      - "${ROPS_PORT}:7777"
    external_links:
      - postgres
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:${POSTGRES_PORT}/${POSTGRES_HOST}?sslmode=disable
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
      - DUMMYUSERIDENTITY=${DUMMY_USER}
      - DUMMYUSERIDENTITY-ALLOWED=true
      - EXPORTFILEDESTINATIONCONFIGFILE=/home/response-operations/dummy_destination_config.json
    restart: always
    healthcheck:
      test: [ "CMD", "java", "/opt/healthcheck/HealthCheck.java", "http://localhost:7777/actuator/health" ]
      interval: 60s
      timeout: 10s
      retries: 4
      start_period: 50s
    volumes:
      - ./java_healthcheck:/opt/healthcheck/
      - ./dummy_destination_config.json:/home/response-operations/dummy_destination_config.json

  notifyservice:
    container_name: notifyservice
    image: europe-west2-docker.pkg.dev/ssdc-rm-ci/docker/ssdc-rm-notify-service
    ports:
      - "${NOTIFY_SERVICE_PORT}:8162"
    external_links:
      - postgres
      - pubsub-emulator
    environment:
      - SPRING_CLOUD_GCP_PUBSUB_EMULATOR_HOST=pubsub-emulator:8538
      - SPRING_CLOUD_GCP_PUBSUB_PROJECT_ID=our-project
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:${POSTGRES_PORT}/${POSTGRES_HOST}?sslmode=disable
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
      - UACSERVICE_CONNECTION_HOST=${UAC_HOST}
      - UACSERVICE_CONNECTION_PORT=${UAC_PORT}
      - EXCEPTIONMANAGER_CONNECTION_HOST=${EXCEPTIONMANAGER_HOST}
      - EXCEPTIONMANAGER_CONNECTION_PORT=${EXCEPTIONMANAGER_PORT}
      - NOTIFY_BASEURL=${NOTIFY_STUB_BASEURL}
    restart: always
    volumes:
      - ./java_healthcheck:/opt/healthcheck/
    healthcheck:
      test: [ "CMD", "java", "/opt/healthcheck/HealthCheck.java", "http://localhost:8162/actuator/health" ]
      interval: 60s
      timeout: 10s
      retries: 4
      start_period: 50s

  jobprocessor:
    container_name: jobprocessor
    image: europe-west2-docker.pkg.dev/ssdc-rm-ci/docker/ssdc-rm-job-processor
    external_links:
      - pubsub-emulator
      - postgres
    environment:
      - SPRING_CLOUD_GCP_PUBSUB_EMULATOR_HOST=pubsub-emulator:8538
      - SPRING_CLOUD_GCP_PUBSUB_PROJECT-ID=our-project
      - QUEUECONFIG_SHARED-PUBSUB-PROJECT=shared-project
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:${POSTGRES_PORT}/${POSTGRES_HOST}?sslmode=disable
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
    restart: always
    healthcheck:
      test: [ "CMD", "find", "/tmp/job-processor-healthy", "-mmin", "-1" ]
      interval: 60s
      timeout: 10s
      retries: 10
      start_period: 45s

networks:
  default:
    external: true
    name: ssdcrmdockerdev_default
volumes:
  dummy_keys:
