version: "3.4"
services:
  caseprocessor:
    container_name: caseprocessor
    image: eu.gcr.io/ssdc-rm-ci/rm/ssdc-rm-caseprocessor
    external_links:
      - postgres
      - uacqid
      - pubsub-emulator
    environment:
      - SPRING_CLOUD_GCP_PUBSUB_EMULATOR_HOST=pubsub-emulator:8538
      - SPRING_CLOUD_GCP_PUBSUB_PROJECT-ID=our-project
      - QUEUECONFIG_SHARED-PUBSUB-PROJECT=shared-project
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:${POSTGRES_PORT}/${POSTGRES_HOST}?sslmode=disable
      - UACSERVICE_CONNECTION_HOST=${UAC_HOST}
      - UACSERVICE_CONNECTION_PORT=${UAC_PORT}
      - EXCEPTIONMANAGER_CONNECTION_HOST=${EXCEPTIONMANAGER_HOST}
      - EXCEPTIONMANAGER_CONNECTION_PORT=${EXCEPTIONMANAGER_PORT}
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
      - CASEREFGENERATORKEY=${CASEREFGENERATORKEY}
      - RAS-RM-SAMPLE-SERVICE_CONNECTION_HOST=host.docker.internal
      - RAS-RM-PARTY-SERVICE_CONNECTION_HOST=host.docker.internal
      - QUEUECONFIG_RAS-RM-PUBSUB-PROJECT=ras-rm-project
    healthcheck:
      test: [ "CMD", "find", "/tmp/case-processor-healthy", "-mmin", "-1" ]
      interval: 60s
      timeout: 10s
      retries: 10
      start_period: 45s


  caseapi:
    container_name: caseapi
    image: eu.gcr.io/ssdc-rm-ci/rm/ssdc-rm-case-api
    ports:
      - "${CASE_API_PORT}:8161"
    external_links:
      - postgres
      - pubsub-emulator
    environment:
      - SPRING_CLOUD_GCP_PUBSUB_EMULATOR_HOST=pubsub-emulator:8538
      - SPRING_CLOUD_GCP_PUBSUB_PROJECT_ID=our-project
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:${POSTGRES_PORT}/${POSTGRES_HOST}?sslmode=disable
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
      - UACSERVICE_CONNECTION_HOST=${UAC_HOST}
      - UACSERVICE_CONNECTION_PORT=${UAC_PORT}
    restart: always
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8161/actuator/health" ]
      interval: 60s
      timeout: 10s
      retries: 4
      start_period: 50s


  uacqid:
    container_name: uacqid
    image: eu.gcr.io/ssdc-rm-ci/rm/ssdc-rm-uac-qid-service
    ports:
      - "${UAC_PORT}:8164"
    external_links:
      - postgres
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:${POSTGRES_PORT}/${POSTGRES_HOST}?sslmode=disable
      - JAVA_TOOL_OPTIONS=-Xmx128m -Xdebug -Dspring.profiles.active=dev
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
    restart: always
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8164/actuator/health" ]
      interval: 60s
      timeout: 10s
      retries: 4
      start_period: 30s


  exceptionmanager:
    container_name: exceptionmanager
    image: eu.gcr.io/ssdc-rm-ci/rm/ssdc-rm-exception-manager
    ports:
      - "${EXCEPTIONMANAGER_PORT}:8666"
    restart: always
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:${POSTGRES_PORT}/${POSTGRES_HOST}?sslmode=disable
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8666/actuator/health" ]
      interval: 60s
      timeout: 10s
      retries: 4
      start_period: 30s


  printfilesvc:
    container_name: printfilesvc
    image: eu.gcr.io/ssdc-rm-ci/rm/ssdc-rm-print-file-service
    external_links:
      - pubsub-emulator
      - sftp
    environment:
      - READINESS_FILE_PATH=/tmp/ready
      - ENVIRONMENT=DEV
      - SFTP_HOST=sftp
      - SFTP_PORT=22
      - SFTP_USERNAME=centos
      - SFTP_KEY_FILENAME=/home/printfile/dummy_keys/dummy_rsa
      - SFTP_PASSPHRASE=dummy_secret
      - EXCEPTIONMANAGER_CONNECTION_HOST=${EXCEPTIONMANAGER_HOST}
      - EXCEPTIONMANAGER_CONNECTION_PORT=${EXCEPTIONMANAGER_PORT}
      - SUPPLIER_CONFIG_JSON_PATH=/home/printfile/dummy_supplier_config.json
      - SUPPLIER_KEY_DIRECTORY=/home/printfile/dummy_keys
      - DB_HOST=${POSTGRES_HOST}
      - DB_PORT=${POSTGRES_PORT}
      - DB_USERNAME=${POSTGRES_USERNAME}
      - DB_PASSWORD=${POSTGRES_PASSWORD}
      - DB_DATABASE=${POSTGRES_DATABASE}
    restart: always
    healthcheck:
      test: sh -c "[ -f /tmp/ready ]"
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 50s
    volumes:
      - ./dummy_keys:/home/printfile/dummy_keys
      - ./dummy_supplier_config.json:/home/printfile/dummy_supplier_config.json


  supporttool:
    container_name: supporttool
    image: eu.gcr.io/ssdc-rm-ci/rm/ssdc-rm-support-tool
    ports:
      - "9999:9999"
    external_links:
      - pubsub-emulator
      - postgres
    environment:
      - SPRING_CLOUD_GCP_PUBSUB_EMULATOR_HOST=pubsub-emulator:8538
      - SPRING_CLOUD_GCP_PUBSUB_PROJECT-ID=our-project
      - QUEUECONFIG_SHARED-PUBSUB-PROJECT=shared-project
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:${POSTGRES_PORT}/${POSTGRES_HOST}?sslmode=disable
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
      - NOTIFYSERVICE_CONNECTION_HOST=${NOTIFY_SERVICE_HOST}
      - NOTIFYSERVICE_CONNECTION_PORT=${NOTIFY_SERVICE_PORT}
      - DUMMYUSERIDENTITY=${DUMMY_USER}
      - DUMMYUSERIDENTITY-ALLOWED=true
      - PRINTSUPPLIERCONFIGFILE=/home/supporttool/dummy_supplier_config.json
      - EXCEPTIONMANAGER_CONNECTION_HOST=${EXCEPTIONMANAGER_HOST}
      - EXCEPTIONMANAGER_CONNECTION_PORT=${EXCEPTIONMANAGER_PORT}
    restart: always
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9999/actuator/health" ]
      interval: 60s
      timeout: 10s
      retries: 4
      start_period: 50s
    volumes:
      - ./dummy_supplier_config.json:/home/supporttool/dummy_supplier_config.json

  rops:
    container_name: rops
    image: eu.gcr.io/ssdc-rm-ci/rm/ssdc-rm-response-operations
    ports:
      - "${ROPS_PORT}:7777"
    external_links:
      - postgres
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:${POSTGRES_PORT}/${POSTGRES_HOST}?sslmode=disable
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
      - DUMMYUSERIDENTITY=${DUMMY_USER}
      - PRINTSUPPLIERCONFIGFILE=/home/response-operations/dummy_supplier_config.json
    restart: always
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:7777/actuator/health" ]
      interval: 60s
      timeout: 10s
      retries: 4
      start_period: 50s
    volumes:
      - ./dummy_supplier_config.json:/home/response-operations/dummy_supplier_config.json

  notifyservice:
    container_name: notifyservice
    image: eu.gcr.io/ssdc-rm-ci/rm/ssdc-rm-notify-service
    ports:
      - "${NOTIFY_SERVICE_PORT}:8162"
    external_links:
      - postgres
      - pubsub-emulator
    environment:
      - SPRING_CLOUD_GCP_PUBSUB_EMULATOR_HOST=pubsub-emulator:8538
      - SPRING_CLOUD_GCP_PUBSUB_PROJECT_ID=our-project
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:${POSTGRES_PORT}/${POSTGRES_HOST}?sslmode=disable
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
      - UACSERVICE_CONNECTION_HOST=${UAC_HOST}
      - UACSERVICE_CONNECTION_PORT=${UAC_PORT}
      - EXCEPTIONMANAGER_CONNECTION_HOST=${EXCEPTIONMANAGER_HOST}
      - EXCEPTIONMANAGER_CONNECTION_PORT=${EXCEPTIONMANAGER_PORT}
      - NOTIFY_BASEURL=${NOTIFY_STUB_BASEURL}
    restart: always
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8162/actuator/health" ]
      interval: 60s
      timeout: 10s
      retries: 4
      start_period: 50s

networks:
  default:
    external:
      name: ssdcrmdockerdev_default
volumes:
  dummy_keys:
